# Generated by Django 5.1.1 on 2024-11-13 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlideShowImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Optional title for the image.', max_length=100, null=True)),
                ('description', models.TextField(blank=True, help_text='Optional description for the image.', null=True)),
                ('image', models.ImageField(help_text='Upload an image for the slideshow.', upload_to='slideshow_images/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of the image in the slideshow.')),
                ('is_active', models.BooleanField(default=True, help_text='Toggle to display or hide this image in the slideshow.')),
            ],
            options={
                'verbose_name': 'Slide Show Image',
                'verbose_name_plural': 'Slide Show Images',
                'ordering': ['order'],
            },
        ),
    ]
