# Generated by Django 5.1.1 on 2024-10-23 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ekart', '0005_alter_cart_user_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='order',
            name='state',
        ),
        migrations.RemoveField(
            model_name='order',
            name='street_address',
        ),
    ]
