# Generated by Django 5.1.1 on 2024-10-23 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ekart', '0010_remove_order_product_remove_order_quantity_orderitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
