# Generated by Django 5.1.1 on 2024-10-26 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekart', '0011_delete_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='enduser',
            name='reset_token',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
