# Generated by Django 5.1.1 on 2024-11-11 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekart', '0017_alter_orderitem_order'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user'], name='ekart_order_user_id_f73f27_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_id'], name='ekart_order_order_i_790fb6_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='ekart_order_status_001e19_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_date'], name='ekart_order_order_d_a4e7ec_idx'),
        ),
    ]
