# Generated by Django 5.1.1 on 2024-11-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekart', '0018_order_ekart_order_user_id_f73f27_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='warranty',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.CharField(max_length=50),
        ),
    ]
