# Generated by Django 5.1.1 on 2024-11-13 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekart', '0021_alter_payment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='enduser',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
