# Generated by Django 5.1.1 on 2024-11-15 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekart', '0022_enduser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offer_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
