# Generated by Django 5.1.1 on 2024-11-16 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekart', '0023_product_offer_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='alternate_contact_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
