# Generated by Django 5.1.1 on 2024-11-20 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekart', '0024_order_alternate_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='estimated_delivery_date',
            field=models.DateField(default="2022-09-22"),
            preserve_default=False,
        ),
    ]
